### ISSUE TITLE
Add support for gpg keys

### ISSUE THREAD

**Issue by izissise** [prydonius/karn#13]

**Comment by prydonius** [comment]
Hey @izissise, thanks for creating the issue! Just to clarify, are you talking about the `user.signingkey` config option in Git?

**Comment by izissise** [comment]
Yup that right, It would be cool if we can sign commits with a gpg key depending on the identity ;)

**Comment by prydonius** [comment]
implemented in #25, thanks @DanielMSchmidt and @izissise!
