### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by captn3m0** [prydonius/karn#15]
The latest release (v0.0.3) is labelled as v0.0.2:

```
karn --version
karn version 0.0.2
```

Noticed this as I was working on the karn AUR package: https://aur.archlinux.org/packages/karn/

**Comment by prydonius** [comment]
thanks for working on the arch linux package! I submitted #16 to fix this, but looks like I need to update the CI build toolchain.

**Comment by prydonius** [comment]
@captn3m0 this has now been fixed, also there's a new 0.0.4 release out now.
