### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by captn3m0** [prydonius/karn#24]
The changes from #19 are missing in the current release.

**Comment by prydonius** [comment]
Hey! https://github.com/prydonius/karn/releases/tag/v0.0.4 contains the changes in #19, or did you mean the more recent switch to go.mod in #22? I'm not sure there needs to be a release for #22 since there is no user-facing change.

**Comment by captn3m0** [comment]
Yes, I meant #22. It will have to packaged differently - thought it might be worth creating a point release so packagers can make those changes now.

**Comment by prydonius** [comment]
@captn3m0 ah I see, sorry I lost track of this. Just created a new release https://github.com/prydonius/karn/releases/tag/v0.0.5!
