### ISSUE TITLE
Should karn unset local identity if it's missing?

### ISSUE THREAD

**Issue by prydonius** [prydonius/karn#3]
At the moment, if a repo doesn't have a matching configuration, karn won't touch the local configuration. Should karn unset the local configuration so that in these cases the default/global identity is always used?

e.g.
1. Set identity in karn.yml
```
/repo:
  name: Adnan A
```
2. Run 
`$ karn update`
3. Remove identity in karn.yml
4. Run 
`$ karn update`

Name is kept as "Adnan A" and not reset back to global/default.

**Comment by mAAdhaTTah** [comment]
I don't think so, if the user sets the repo config themselves, karn shouldn't unset it on them.

**Comment by prydonius** [comment]
I guess you're right, it would be good keep karn non-destructive. closing for now.
