### ISSUE TITLE
Add to Homebrew?

### ISSUE THREAD

**Issue by mAAdhaTTah** [prydonius/karn#8]
Not much more to add, just wondering if you can add this so it can be installed via `brew install karn`.

**Comment by prydonius** [comment]
Thanks for the suggestion! I was reading the Homebrew documentation and it states:
> We frown on authors submitting their own work unless it is very popular.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff

I'm not sure what they consider 'popular', perhaps if there was a lot of interest we could add a formula upstream. In the meantime however, I am considering creating a tap for karn.

**Comment by mAAdhaTTah** [comment]
A tap would be just as useful to me as submitting upstream, so whichever you prefer. I don't know what the level of popularity for this project is, nor their "threshold," but may be worth trying to push upstream first then make the tap if they don't accept. The repo does have 150 stars + I found out about it in a newsletter (so it's got some pickup) so yes, it's "niche" but still somewhat popular.

Either way works for me (and I presume other Homebrew users). Thanks!

**Comment by prydonius** [comment]
Submitted the formula upstream

**Comment by mAAdhaTTah** [comment]
It's in!
